# Generated by Django 6.0.7 on 2026-09-21 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockloss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('git', 'GIT (Good in transit)'), ('approved', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
