# Generated by Django 6.0.7 on 2026-09-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_it_profiles'),
        ('catalog', '0002_branch_api_key_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Required for Sales Admin, Sales, and Stockist. Ignored for org-wide roles.', related_name='portal_users', to='catalog.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('IT', 'IT'), ('Business Head', 'Business Head'), ('Commercial Manager', 'Commercial Manager'), ('Sales Admin', 'Sales Admin'), ('Sales', 'Sales'), ('Stockist', 'Stockist')], default='Sales', max_length=40),
        ),
    ]
