# Generated by Django 6.0.7 on 2026-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='api_key_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='api_key_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
